### ISSUE TITLE
Does not build with NCURSES_REENTRANT

### ISSUE THREAD

**Issue by tjol** [VorpalBlade/cfunge#2]
On my system, which is running OpenSUSE Tumbleweed with `ncurses-devel-6.2.20210718-23.1.x86_64`, cfunge fails to build with an error like this:

```
[ 47%] Building C object CMakeFiles/cfunge.dir/src/fingerprints/NCRS/NCRS.c.o
/home/tjol/code/cfunge/src/fingerprints/NCRS/NCRS.c: In function ‘finger_NCRS_init’:
/home/tjol/code/cfunge/src/fingerprints/NCRS/NCRS.c:144:32: error: lvalue required as left operand of assignment
  144 |                         stdscr = ncrs_window;
      |                                ^
make[2]: *** [CMakeFiles/cfunge.dir/build.make:454: CMakeFiles/cfunge.dir/src/fingerprints/NCRS/NCRS.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:133: CMakeFiles/cfunge.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

It looks like this is because my system has a reentrant build of ncurses, in which global variables (like `stdscr`) are not actually global variables, but function calls disguised as variables using macros

**Comment by VorpalBlade** [comment]
Hi,

It has been a while since I worked on cfunge. I'm currently very busy with my PhD but hopefully I can get back to you next week.

**Comment by tjol** [comment]
Don't worry about it. There's no rush. Focus on your PhD, maybe come back and have a look at the issue when you have nothing better to do. There's no reason it has to be anytime soon as far as I'm concerned :-)

**Comment by VorpalBlade** [comment]
I have not been able to find much information on this reentrant ncurses but I found [this](https://github.com/mirror/ncurses):

> If you configure using the --enable-reentrant option, a "t" is appended to the
> library names (e.g., libncursest.a) and the resulting libraries have a
> different binary interface which makes the ncurses interface more "opaque".

This makes me confused. If the library name is different, shouldn't the two libraries be able to co-exist side by side? And since the CMake file links ncurses (not ncursest), this should work fine? Possibly a check for the ncurses library, not just the ncurses headers needs to be added though. There is already ncurses and ncursesw that can co-exist like this (according to the debian package dependencies at least).

Besides, if this is API incompatible (the quoted text above only refers to ABI incompatibility) this should break a lot of software presumably.

**Comment by tjol** [comment]
My impression is (and I know very little about the ncurses API) that this is API compatible *unless* you assign to certain global variables, which most software doesn't do (any more). I believe there are other functions or macros that allow you to achieve the same effect.

I've only been able to divine that this is the issue from a handful of patches to other software making it compatible with NCURSES_REENTRANT (from googling phrases like "stdscr lvalue").

As for the library name, I've had a quick look at the ncurses `configure.in` file, and it looks like the library name is only changed if and only if “weak symbols” are disabled, whatever that means. https://github.com/mirror/ncurses/blob/master/configure.in#L1338

(And weak symbols are enabled in the OpenSUSE RPM, see https://build.opensuse.org/package/view_file/Base:System/ncurses/ncurses.spec?expand=1)

No idea how common this configuration is on other distributions.

**Comment by VorpalBlade** [comment]
I merged your workaround. I looked at the documentation (for a somewhat short time mind you), and I don't see any description of how to do with the newer API what I did with the non-reentrant API. Maybe it isn't possible?

If you have any ideas or suggestions, feel free to provide them. From what I remember I need to save/restore the state of ncurses as the funge API allows enabling/disabling it arbitrarily. Thus going back and forth between "normal terminal with working scrollback" and "ncurses window mode". I *think* that is what I needed that stuff for.

**Comment by tjol** [comment]
Whatever it was for, it wasn't switching in and out of curses mode at will, because that's not actually something cfunge supports ( https://github.com/VorpalBlade/cfunge/blob/master/src/fingerprints/NCRS/NCRS.c#L132 )

This example program, for example, will quite happily switch in and out of curses mode in rcFunge, but not in cfunge:
```
'd.a,~ "SRCN"4#v(>1I0C11M'xPRGR0v
v    "no NCRS"0<           v-q'I<
>:#,_@   >:#,_v#:"again!"0$_
              a  #
              >,~^
```
(press `q` in curses mode to exit the loop if you try this)

I've looking into it and I think I've managed to take out the global assignments without breaking anything. Pull request coming in a bit.
